server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: icebreakers
    password: anonymous
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true