on:
  workflow_run:
    types:
      - completed
    workflows:
      - BuildAndTest

name: CoverageCheck
run-name: Coverage Check

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy_qa"

  sanity:
    runs-on: ubuntu-latest
    needs: deploy_qa
    steps:
      - run: echo "Running Sanity tests in QA"

  uat_test:
    runs-on: ubuntu-latest
    needs: deploy_qa
    steps:
      - run: echo "uat_test"